channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.5.2
  - sphinx>1.4
  - pandoc
  - nbconvert
  - ipykernel
  - pandas
  - holoviews
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - bokeh
  - nbsphinx
